### ISSUE TITLE
Ligação de todo código

### ISSUE THREAD

**Issue by HiloGoes** [vna15/SD_CDA_IMPLEMENTACAO#1]
### Estabelecer
- [ ] Parâmetros para transmissão de mensagem 
- [ ] Retornos de comunicação TWI-I2C
- [ ] Conexão de RTC e UART

### MDE
- [x] Enviar para display **estado atual**
- [ ] Desenvolver rotina de conexão entre RTC e **log** UART

### INTERRUPÇÃO
- [x] Elaborar lógica para execução de rotina para verificação do pressionamento de botões por interrupção
- [x] Configurar interrupção do pino DA do teclado, para ser acionado apenas na borda de subida  

### SENSORIAMENTO E ZONAS
- [ ] Definir lógica do acionamento dos leds por zonas
- [ ] Leitura do Port B e concatenação dos sensores ativados
- [x] Verificar se acionado é 0 ou 1 para sensores comerciais
